name: week09
channels:
- conda-forge
- defaults
dependencies:
- boost-cpp=1.67.0
- bzip2=1.0.6
- curl=7.60.0
- expat=2.2.5
- freetype=2.8.1
- freexl=1.0.5
- gdal=2.3.1
- geos=3.6.2
- geotiff=1.4.2
- hdf4=4.2.13
- hdf5=1.10.2
- icu=58.2
- jpeg=9c
- kealib=1.4.9
- krb5=1.14.6
- libgdal=2.3.1
- libkml=1.3.0
- libnetcdf=4.6.1
- libpng=1.6.34
- libpq=9.6.3
- libsodium=1.0.16
- libspatialite=4.3.0a
- libtiff=4.0.9
- libxslt=1.1.32
- lzo=2.10
- matplotlib=2.2.2
- openjpeg=2.3.0
- openssl=1.0.2p
- pcre=8.41
- postgresql=10.3
- proj4=4.9.3
- qt=5.6.2
- snappy=1.1.7
- sqlite=3.25.3
- tk=8.6.8
- xerces-c=3.2.0
- xz=5.2.4
- yaml=0.1.7
- zeromq=4.2.5
- zlib=1.2.11
- alabaster=0.7.10
- anaconda-client
- anaconda=custom
- anaconda-project=0.8.2
- asn1crypto=0.24.0
- astroid=1.6.3
- astropy=3.0.2
- attrs=18.1.0
- babel=2.5.3
- backcall=0.1.0
- backports=1.0
- backports.shutil_get_terminal_size=1.0.0
- beautifulsoup4=4.6.0
- bitarray=0.8.1
- bkcharts=0.2
- blas=1.0
- blaze=0.11.3
- bleach=2.1.3
- blosc=1.14.3
- bokeh=0.12.16
- boto=2.48.0
- bottleneck=1.2.1
- ca-certificates
- certifi=2018.4.16
- cffi=1.11.5
- chardet=3.0.4
- click=6.7
- cloudpickle=0.5.3
- clyent=1.2.2
- colorama=0.3.9
- comtypes=1.1.4
- console_shortcut=0.1.1
- contextlib2=0.5.5
- cryptography=2.2.2
- cycler=0.10.0
- cython=0.28.2
- cytoolz=0.9.0.1
- dask=0.17.5
- dask-core=0.17.5
- datashape=0.5.4
- decorator=4.3.0
- distributed=1.21.8
- docutils=0.14
- entrypoints=0.2.3
- et_xmlfile=1.0.1
- fastcache=1.0.2
- filelock=3.0.4
- flask=1.0.2
- flask-cors=3.0.4
- get_terminal_size=1.0.0
- gevent=1.3.0
- glob2=0.6
- greenlet=0.4.13
- h5py=2.7.1
- heapdict=1.0.0
- html5lib=1.0.1
- icc_rt=2017.0.4
- idna=2.6
- imageio=2.3.0
- imagesize=1.0.0
- intel-openmp=2018.0.0
- ipykernel=4.8.2
- ipython=6.4.0
- ipython_genutils=0.2.0
- ipywidgets=7.2.1
- isort=4.3.4
- itsdangerous=0.24
- jdcal=1.4
- jedi=0.12.0
- jinja2=2.10
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.3
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- jupyterlab=0.32.1
- jupyterlab_launcher=0.10.5
- kiwisolver=1.0.1
- lazy-object-proxy=1.3.1
- libcurl=7.60.0
- libiconv=1.15
- libssh2=1.8.0
- libxml2=2.9.8
- llvmlite=0.23.1
- locket=0.2.0
- lxml=4.2.1
- m2w64-expat=2.1.1
- m2w64-gcc-libgfortran=5.3.0
- m2w64-gcc-libs=5.3.0
- m2w64-gcc-libs-core=5.3.0
- m2w64-gettext=0.19.7
- m2w64-gmp=6.1.0
- m2w64-libiconv=1.14
- m2w64-libwinpthread-git=5.0.0.4634.697
- m2w64-xz=5.2.2
- markupsafe=1.0
- mccabe=0.6.1
- menuinst=1.4.14
- mistune=0.8.3
- mkl=2019.0
- mkl-service=1.1.2
- mkl_fft=1.0.1
- mkl_random=1.0.1
- more-itertools=4.1.0
- mpmath=1.0.0
- msgpack-python=0.5.6
- msys2-conda-epoch=20160418
- multipledispatch=0.5.0
- nbconvert=5.3.1
- nbformat=4.4.0
- networkx=2.1
- nltk=3.3.0
- nose=1.3.7
- notebook=5.5.0
- numba=0.38.0
- numexpr=2.6.5
- numpy=1.14.6
- numpy-base=1.14.6
- numpydoc=0.8.0
- odo=0.5.1
- olefile=0.45.1
- openpyxl=2.5.3
- packaging=17.1
- pandas=0.23.0
- pandoc=1.19.2.1
- pandocfilters=1.4.2
- parso=0.2.0
- partd=0.3.8
- path.py=11.0.1
- pathlib2=2.3.2
- patsy=0.5.0
- pep8=1.7.1
- pickleshare=0.7.4
- pillow=5.1.0
- pip=10.0.1
- pkginfo=1.4.2
- pluggy=0.6.0
- ply=3.11
- prompt_toolkit=1.0.15
- psutil=5.4.5
- py=1.5.3
- pycodestyle=2.4.0
- pycosat=0.6.3
- pycparser=2.18
- pycrypto=2.6.1
- pycurl=7.43.0.1
- pyflakes=1.6.0
- pygments=2.2.0
- pylint=1.8.4
- pyodbc=4.0.23
- pyopenssl=18.0.0
- pyparsing=2.2.0
- pyqt=5.6.0
- pysocks=1.6.8
- pytables=3.4.3
- pytest=3.5.1
- pytest-arraydiff=0.2
- pytest-astropy=0.3.0
- pytest-doctestplus=0.1.3
- pytest-openfiles=0.3.0
- pytest-remotedata=0.2.1
- python=3.5.5
- python-dateutil=2.7.3
- pytz=2018.4
- pywavelets=0.5.2
- pywin32=223
- pywinpty=0.5.1
- pyyaml=3.12
- pyzmq=17.0.0
- qtawesome=0.4.4
- qtconsole=4.3.1
- qtpy=1.4.1
- requests=2.18.4
- rope=0.10.7
- ruamel_yaml=0.15.35
- scikit-image=0.13.1
- scikit-learn=0.19.1
- scipy=1.1.0
- seaborn=0.8.1
- send2trash=1.5.0
- setuptools=39.1.0
- simplegeneric=0.8.1
- singledispatch=3.4.0.3
- sip=4.19.8
- six=1.11.0
- snowballstemmer=1.2.1
- sortedcollections=0.6.1
- sortedcontainers=1.5.10
- sphinx=1.7.4
- sphinxcontrib=1.0
- sphinxcontrib-websupport=1.0.1
- spyder=3.2.8
- sqlalchemy=1.2.7
- statsmodels=0.9.0
- sympy=1.1.1
- tblib=1.3.2
- terminado=0.8.1
- testpath=0.3.1
- toolz=0.9.0
- tornado=5.0.2
- traitlets=4.3.2
- typing=3.6.4
- unicodecsv=0.14.1
- urllib3=1.22
- vc=14
- vs2015_runtime=14.0.25123
- wcwidth=0.1.7
- webencodings=0.5.1
- werkzeug=0.14.1
- wheel=0.31.1
- widgetsnbextension=3.2.1
- win_inet_pton=1.0.1
- win_unicode_console=0.5
- wincertstore=0.2
- winpty=0.4.3=4
- wrapt=1.10.11
- xlrd=1.1.0
- xlsxwriter=1.0.4
- xlwings=0.11.8
- xlwt=1.3.0
- zict=0.1.3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - jupyterlab-launcher==0.10.5
  - mkl-fft==1.0.0
  - mkl-random==1.0.1
  - prompt-toolkit==1.0.15
  - ruamel-yaml==0.15.35
  - tables==3.4.3
  - win-inet-pton==1.0.1
  - win-unicode-console==0.5